os:
  - linux

language: python

python:
  - 3.6
  - nightly
  - pypy3

install:
  - make install-packages
  - pip install python-coveralls

script:
  - make check
  - nosetests
  - coverage run --source=. -m unittest discover

after_success:
  - coveralls
